// lib/pulse/deliver.ts
import { createServiceClient } from '@/lib/supabase/service'

export interface DeliverPulseOptions {
  orgId: string
  customerId: string
  assignedRepId?: string | null
  triggerType: 'sold' | 'manual' | 'day30' | 'day180'
  customerPhone?: string | null
  customerName?: string
}

export async function deliverPulseSurvey(opts: DeliverPulseOptions): Promise<{ token: string } | null> {
  const { orgId, customerId, triggerType } = opts
  const supabase = createServiceClient()

  // Check pulse is enabled for this org
  const { data: settings } = await supabase
    .from('org_settings')
    .select('pulse_enabled, pulse_auto_send_on_sold, twilio_phone_number, business_name')
    .eq('org_id', orgId)
    .maybeSingle()

  if (!settings?.pulse_enabled) return null

  // Gate on active subscription — do not burn Twilio credits for canceled/free orgs
  const { data: org } = await supabase
    .from('organizations')
    .select('subscription_status')
    .eq('id', orgId)
    .single()

  if (!org || !['active', 'trialing'].includes(org.subscription_status ?? '')) {
    return null
  }

  // Respect per-trigger-type settings
  if (triggerType === 'sold' && settings.pulse_auto_send_on_sold === false) return null

  // Guard: no duplicate survey for same customer + trigger type within 7 days
  const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString()
  const { data: existing } = await supabase
    .from('pulse_surveys')
    .select('id')
    .eq('org_id', orgId)
    .eq('customer_id', customerId)
    .eq('trigger_type', triggerType)
    .gte('created_at', sevenDaysAgo)
    .maybeSingle()

  if (existing) return null

  // Fetch customer details from DB when not provided by caller
  let phone = opts.customerPhone ?? null
  let name  = opts.customerName  ?? ''
  let repId = opts.assignedRepId ?? null

  if (!name || phone === undefined) {
    const { data: cust } = await supabase
      .from('customers')
      .select('name, primary_phone, assigned_to')
      .eq('id', customerId)
      .maybeSingle()
    if (!name)           name  = cust?.name ?? ''
    if (phone === null)  phone = cust?.primary_phone ?? null
    if (repId === null)  repId = cust?.assigned_to ?? null
  }

  // Create survey record (token auto-generated by DB default)
  const { data: survey, error } = await supabase
    .from('pulse_surveys')
    .insert({
      org_id:          orgId,
      customer_id:     customerId,
      assigned_rep_id: repId,
      trigger_type:    triggerType,
      sent_at:         new Date().toISOString(),
    })
    .select('id, token')
    .single()

  if (error || !survey) return null

  const appUrl    = process.env.NEXT_PUBLIC_APP_URL ?? 'https://dealerwyze.com'
  const surveyUrl = `${appUrl}/pulse/${survey.token}`
  const firstName = name.split(' ')[0] || 'there'
  const bizName   = settings.business_name || 'the dealership'

  // Send SMS via Twilio REST API (non-blocking — survey already created above)
  const twilioSid   = process.env.TWILIO_ACCOUNT_SID
  const twilioToken = process.env.TWILIO_AUTH_TOKEN
  if (phone && settings.twilio_phone_number && twilioSid && twilioToken) {
    try {
      await fetch(
        `https://api.twilio.com/2010-04-01/Accounts/${twilioSid}/Messages.json`,
        {
          method:  'POST',
          headers: {
            'Content-Type':  'application/x-www-form-urlencoded',
            'Authorization': `Basic ${Buffer.from(`${twilioSid}:${twilioToken}`).toString('base64')}`,
          },
          body: new URLSearchParams({
            To:   phone,
            From: settings.twilio_phone_number,
            Body: `Hi ${firstName}! Thank you for your recent purchase at ${bizName}. Your experience matters to us. Please take a moment to share your feedback: ${surveyUrl}`,
          }),
        }
      )
    } catch {
      // Non-blocking — do not propagate SMS errors
    }
  }

  return { token: survey.token }
}
