import type { VerticalConfig } from './types'

export const dealerConfig: VerticalConfig = {
  vertical: 'dealer',
  brandName: 'DealerWyze',
  domain: 'dealerwyze.com',
  tagline: 'CRM for independent used-car dealers',
  labels: {
    inventory: 'Inventory',
    inventoryItem: 'Vehicle',
    inventoryItems: 'Vehicles',
    inventoryId: 'Stock #',
    propertyId: 'VIN',
    contact: 'Customer',
    contacts: 'Customers',
    lead: 'Lead',
    leads: 'Leads',
    orgName: 'Dealership',
    rep: 'Sales Rep',
    repPlural: 'Sales Reps',
    admin: 'Dealer Admin',
    pipelineItem: 'Deal',
    bhphModule: 'BHPH',
    contentReel: 'Vehicle Reel',
    inboxName: 'Dealer Inbox',
    wantsModule: 'Vehicle Wants',
    publicPage: 'Dealer Website',
    kpiVolume: 'Cars Sold',
    kpiInventory: 'Vehicles in Stock',
    kpiRevenue: 'Gross Profit',
    kpiConversion: 'Lead-to-Sale Rate',
    kpiDays: 'Avg Days to Sell',
  },
  features: {
    bhph: true,
    fax: true,
    vinScanner: true,
    recon: true,
    cargurusFeed: true,
    marketCheck: true,
    showings: false,
    mlsSync: false,
    buyerCriteria: false,
    commissionMgmt: false,
    leaseManagement: false,
  },
  pipelineDefaults: [
    'new_lead', 'contacted', 'appointment_set', 'appointment_done',
    'working_deal', 'financing', 'closed', 'lost',
  ],
  leadSources: [
    'CarGurus', 'AutoTrader', 'Facebook Marketplace', 'Cars.com',
    'OfferUp', 'Walk-in', 'Phone', 'Referral',
  ],
}
