import type { VerticalConfig } from './types'

export const realEstateConfig: VerticalConfig = {
  vertical: 'real_estate',
  brandName: 'RealtyWyze',
  domain: 'realtywyze.us',
  tagline: 'CRM for independent real estate brokerages',
  labels: {
    inventory: 'Listings',
    inventoryItem: 'Listing',
    inventoryItems: 'Listings',
    inventoryId: 'MLS #',
    propertyId: 'Parcel ID',
    contact: 'Client',
    contacts: 'Clients',
    lead: 'Prospect',
    leads: 'Prospects',
    orgName: 'Brokerage',
    rep: 'Agent',
    repPlural: 'Agents',
    admin: 'Broker',
    pipelineItem: 'Transaction',
    bhphModule: 'Lease Management',
    contentReel: 'Property Reel',
    inboxName: 'Agent Inbox',
    wantsModule: 'Buyer Criteria',
    publicPage: 'Agent Profile',
    kpiVolume: 'Closings',
    kpiInventory: 'Active Listings',
    kpiRevenue: 'GCI',
    kpiConversion: 'Lead-to-Close Rate',
    kpiDays: 'Avg Days on Market',
  },
  features: {
    bhph: false,
    fax: false,
    vinScanner: false,
    recon: false,
    cargurusFeed: false,
    marketCheck: false,
    showings: true,
    mlsSync: true,
    buyerCriteria: true,
    commissionMgmt: true,
    leaseManagement: true,
  },
  pipelineDefaults: [
    'new_inquiry', 'contacted', 'showing_set', 'showing_done',
    'offer_submitted', 'under_contract', 'pending_inspection', 'closed', 'lost',
  ],
  leadSources: [
    'Zillow', 'Realtor.com', 'Homes.com', 'Facebook',
    'Instagram', 'Open House', 'Sign Call', 'Referral', 'Web Form',
  ],
}
